/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uit.tkorg.and.gui;

import java.io.File;
import java.util.Enumeration;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import uit.tkorg.and.models.Feature;

/**
 *
 * @author tiendv
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTrainingDataParth = new javax.swing.JTextField();
        tfTestDataParth = new javax.swing.JTextField();
        btTrainingDataParth = new javax.swing.JButton();
        btTestDataParth = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbJaccardAuthorName = new javax.swing.JCheckBox();
        cbJaccardAfiliation = new javax.swing.JCheckBox();
        cbJaccardCoAuthor = new javax.swing.JCheckBox();
        cbJaccardKeyword = new javax.swing.JCheckBox();
        cbJaccardKeyInteresting = new javax.swing.JCheckBox();
        cbLevenshteinAuthorName = new javax.swing.JCheckBox();
        cbLevenshteinAfflicaiton = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        rbRF = new javax.swing.JRadioButton();
        rbSVM = new javax.swing.JRadioButton();
        rbBayes = new javax.swing.JRadioButton();
        btRun = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        jLabel1.setText("Training Data");

        jLabel2.setText("Test Data");

        btTrainingDataParth.setText("Open");
        btTrainingDataParth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrainingDataParthActionPerformed(evt);
            }
        });

        btTestDataParth.setText("Open");
        btTestDataParth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestDataParthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTrainingDataParth)
                    .addComponent(tfTestDataParth, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTrainingDataParth)
                    .addComponent(btTestDataParth))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTrainingDataParth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTrainingDataParth))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTestDataParth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTestDataParth))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Features"));

        cbJaccardAuthorName.setText("JCAuthorName");

        cbJaccardAfiliation.setText("JCAffiliation ");

        cbJaccardCoAuthor.setText("JCCoAuthor");

        cbJaccardKeyword.setText("JCKeyWord");

        cbJaccardKeyInteresting.setText("JCKeyInteresting");

        cbLevenshteinAuthorName.setText("LevenshteinAuthor");
        cbLevenshteinAuthorName.setToolTipText("");

        cbLevenshteinAfflicaiton.setText("LvAffiliation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbLevenshteinAuthorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbLevenshteinAfflicaiton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbJaccardAuthorName)
                        .addGap(18, 18, 18)
                        .addComponent(cbJaccardAfiliation)
                        .addGap(18, 18, 18)
                        .addComponent(cbJaccardCoAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(cbJaccardKeyword)
                        .addGap(18, 18, 18)
                        .addComponent(cbJaccardKeyInteresting)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJaccardAuthorName)
                    .addComponent(cbJaccardAfiliation)
                    .addComponent(cbJaccardCoAuthor)
                    .addComponent(cbJaccardKeyword)
                    .addComponent(cbJaccardKeyInteresting))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLevenshteinAuthorName)
                    .addComponent(cbLevenshteinAfflicaiton))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Classifiers"));

        buttonGroup1.add(rbRF);
        rbRF.setText("Random Forest");

        buttonGroup1.add(rbSVM);
        rbSVM.setText("SVM");

        buttonGroup1.add(rbBayes);
        rbBayes.setText("Bayes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(rbRF)
                .addGap(118, 118, 118)
                .addComponent(rbSVM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(rbBayes)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRF)
                    .addComponent(rbSVM)
                    .addComponent(rbBayes)))
        );

        btRun.setText("RUN");
        btRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btRun, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRun)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTrainingDataParthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrainingDataParthActionPerformed
        // TODO add your handling code here:
        

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.showOpenDialog(this);  
        // Show open dialog; this method does not return until the dialog is closed       
        tfTrainingDataParth.setText(fc.getCurrentDirectory().toString());
    }//GEN-LAST:event_btTrainingDataParthActionPerformed

    private void btTestDataParthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestDataParthActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.showOpenDialog(this);  
        // Show open dialog; this method does not return until the dialog is closed       
        tfTestDataParth.setText(fc.getCurrentDirectory().toString());
    }//GEN-LAST:event_btTestDataParthActionPerformed

    private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed
        // TODO add your handling code here:
        
        // Get path data
        String pathForTrain = tfTrainingDataParth.getText();
        String pathForTest = tfTestDataParth.getText();
        
        //Get Feature
        
        Feature selectFeatures = new Feature();
        int dimension =0;
        
        // Jaccard Authorname
        if(cbJaccardAuthorName.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setJcAuthorName(true);
        }
        // Jaccard Coauthor 
        if(cbJaccardCoAuthor.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setJcCoAuthor(true);
        }
          // Jaccard Afiliation
        if(cbJaccardAfiliation.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setJcAffiliation(true);
        }
          // Jaccard keword
        if(cbJaccardKeyword.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setJcKeyword(true);
        }
          // Jaccard Interesting
        if(cbJaccardKeyInteresting.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setJcInterestingKeyword(true);
        }
        
          // Levenshtein Author name
        if(cbLevenshteinAuthorName.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setLevenshteinAuthorname(true);
        }
          // Levenshtein Affilication
        if(cbLevenshteinAfflicaiton.isSelected())
        {
            dimension ++;
            selectFeatures.setNumberSelectFeature(dimension);
            selectFeatures.setLevenshteinAffiliaiton(true);
        }
        
        // Add more feature here
        
        // Get Classifier
        JRadioButton nameClassifier = getSelection(buttonGroup1);
        
        // Call caculate and show the result
    }//GEN-LAST:event_btRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    public static JRadioButton getSelection(ButtonGroup group) {
    for (Enumeration e=group.getElements(); e.hasMoreElements(); ) {
        JRadioButton b = (JRadioButton)e.nextElement();
        if (b.getModel() == group.getSelection()) {
            return b;
        }
    }
    return null;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRun;
    private javax.swing.JButton btTestDataParth;
    private javax.swing.JButton btTrainingDataParth;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbJaccardAfiliation;
    private javax.swing.JCheckBox cbJaccardAuthorName;
    private javax.swing.JCheckBox cbJaccardCoAuthor;
    private javax.swing.JCheckBox cbJaccardKeyInteresting;
    private javax.swing.JCheckBox cbJaccardKeyword;
    private javax.swing.JCheckBox cbLevenshteinAfflicaiton;
    private javax.swing.JCheckBox cbLevenshteinAuthorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbBayes;
    private javax.swing.JRadioButton rbRF;
    private javax.swing.JRadioButton rbSVM;
    private javax.swing.JTextField tfTestDataParth;
    private javax.swing.JTextField tfTrainingDataParth;
    // End of variables declaration//GEN-END:variables
}
